### PR TITLE
Adds the use of -j,--json to include JSON data when deploying a project

### PR DESCRIPTION
**Pull request by license2e**
Adds the use of -j,--json to include JSON data to be merged into the generated package.json when deploying a project.

### CODE REVIEW

**Comment by yoepus** [comment]
+1 would like to see this as well

**Comment by tzmanics** [comment]
@license2e thanks for doing this! I'll get with the team today and see if they have any feedback on this idea.

**Comment by tzmanics** [comment]
Hi @license2e & @yoepus 👋 We're finally starting to catch up to these now, thanks for your input and contributing!

Is this feature focused on Meteor projects?

**Comment by license2e** [comment]
@tzmanics Yes, that is correct, its present in the `demeteorizer` lib/action and this pull request adds it as an option to the `modulus-cli`.

With release of meteor 1.3 it may no longer be needed, but for older versions it definitely comes in handy.

**Comment by tzmanics** [comment]
Great thanks @license2e I'm trying to do a few tests on it. Could you give me a few example commands you would use with `-j`. Thanks!

**Comment by jackboberg** [comment]
Related, there is a [`TODO`](https://github.com/onmodulus/docker-build-meteor/blob/master/bin/build#L28) on the new meteor build image to support this.

**Comment by license2e** [comment]
@tzmanics We currently use it like this:

```
modulus deploy -j include.json -p 'NameOfProject'
```

Our `include.json` contains the following code:

```
{
  "version": "1.0.0",
  "engines": {
    "node": "0.10.40"
  },
  "dependencies": {
    "..."
  }
}
```

And the expectation is that `package.json` would contain everything that was in the `include.json` file once the project was `demeteorized` and uploaded to modulus.

**Comment by tzmanics** [comment]
Does anyone have a good reason to implement this here as well since we're planning on adding it to the new meteor build image?

**Comment by harlanj** [comment]
It would need to be added here to pass the user's desired json content to the `demeteorize` command.

**Comment by license2e** [comment]
@tzmanics Are you saying that you are planning to just add the whole package.json to the meteor build image instead of using -j option? If so, then there is no reason to add this here.

**Comment by tzmanics** [comment]
Hey all, sorry it's been a while. @harlanj were you saying we would still need to do it through the `cli`?

**Comment by harlanj** [comment]
@tzmanics yes

**Comment by license2e** [comment]
@tzmanics Do you need me to to fix the conflict? or have you found another way to just include the `package.json` into the demeteorized package?

**Comment by tzmanics** [comment]
@license2e We'd love to have your contribution. If you fix the conflict we'll go ahead and review and test on our end. Thanks!

**Comment by tzmanics** [comment]
Hey @license2e my co-worker, @harlanj, just reminded me that we would have to build out the accompanying tool to accept this new flag. Once we have that done we'll get this tested and keep you updated.

Thanks again for your contribution!

**Pull request closed without merging**
