### PR TITLE
Attempt to force Meteor version into semver

### LINKED ISSUE #128: Meteor 1.4
Deploying to Meteor runtime environment with CLI I get this error

```
/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 1.4

    at new SemVer (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:293:11)
    at compare (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:566:10)
    at Function.gte (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:615:10)
    at Project.isSupported (/usr/local/lib/node_modules/modulus/lib/controllers/project.js:771:17)
    at /usr/local/lib/node_modules/modulus/lib/controllers/project.js:246:34
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

### PR DESCRIPTION
**Pull request by jackboberg**
- [x] needs testing

Closes #128

### CODE REVIEW

**Comment by musgravejw** [comment]
Worth a shot.  Curious what formats this will support, and what will break.

**Comment by jackboberg** [comment]
There is an issue with this approach if `Meteor` releases a version with a string in one of the 1st three positions (eg: `1.5.beta`, `2-alpha`)

**Comment by musgravejw** [comment]
Could we check if the `patch

**Comment by musgravejw** [comment]
Could we check if the patch is numeric, else, truncate to minor?

**Comment by fiveisprime** [comment]
What is this code actually trying to accomplish?

Seems like this is verifying that a specific version is supported on Modulus so.. does the check really _need_ to be infinitely flexible?

**Comment by jackboberg** [comment]
Was just looking into parsing to integer, I think that can work:

```
> parseInt('2-alpha', 10)
2
> parseInt('beta', 10)
NaN
```

Just need to convert `NaN` to `0` I think

**Comment by jackboberg** [comment]
@fiveisprime are you suggesting a whitelist lookup instead? We'd have to update for every release, and every user would need to update to deploy, right?

**Comment by jackboberg** [comment]
updated with attempt to `parseInt` and included test.

**Comment by harlanj** [comment]
My be redundant, but another test with the version being `2` or `x`. Besides that, 👍

**Comment by fiveisprime** [comment]
LGTM

**Comment by jackboberg** [comment]
added some failing non-server tests and included more options recommended by @harlanj

**Comment by musgravejw** [comment]
👍

**Comment by jackboberg** [comment]
I think we publish this as `6.2.1` and `next` on npm, let @flean and @hassanasad try it out

**Comment by fiveisprime** [comment]
Could always have them `$ npm install -g onmodulus/modulus-cli#bug/meteor-version` to test

**Comment by harlanj** [comment]
I think #132 needs to be in that patch as well, since it was introduced in `v6.2.0`

**Comment by timmyg** [comment]
Is this deployed to npm? I tried downloading the latest, and also modulus@next. Also tried with #bug/meteor-version but looks like that branch doesnt exist anymore. @fiveisprime @jackboberg

**Comment by harlanj** [comment]
This is in the `master` branch. Just update to pull from master @timmyg

**Comment by timmyg** [comment]
@harlanj ah sweet, looks like its working now. Do you know if there is any way to force a version on Codeship? (at least i can deploy now, just have to do it manually)

**Comment by harlanj** [comment]
I'm not sure on how to do that. I haven't done any Codeship integrations. If you want to hop in our irc I can try to help you more there.

**Comment by timmyg** [comment]
@harlanj cool, will hop in there in a bit - thanks for the help!

**Comment by pietro1412** [comment]
What's next step?I updated Modulus on npm. Now?

**Comment by harlanj** [comment]
You can get this update by `npm i -g modulus@next`. However, our build image doesn't yet support Meteor using `node@4`. We have an open issue that addresses this on our [meteor build image](https://github.com/onmodulus/docker-build-meteor/issues/25), but in the meantime, there are other work arounds.

**Comment by byennen** [comment]
:+1:

**Comment by flean** [comment]
Does this work yet? Haven't tried and I'd like to save myself the grief if it doesn't

**Pull request merged**
