### PR TITLE
-s command line option for log streaming

### PR DESCRIPTION
**Pull request by calendee**
Allow use of -s option on command line to allow for auto selection of servo number.

ex : modulus project logs tail -p xxxx -s 2

Signed-off-by: Justin Noel <github@calendee.com>

### CODE REVIEW

**Comment by tzmanics** [comment]
Hi Calendee, thanks for contributing!! We're hoping to get caught up now ☺️ We're a little hesitant on adding this feature because the servo number order can change when projects are scaled and the numbers won't represent the same servo id when a project is stopped and started. Using the servo number is not as reliable as using the servo id. 

We definitely want to add features that help you out so let us know your thoughts on this. Thanks again!

**Comment by calendee** [comment]
Thanks for getting back to me.  If servo index is not reliable, the PR has little value because ... who really keeps track of their servo id's and could remember them enough to enter from memory at the command line.

Feel free to close then.

**Comment by tzmanics** [comment]
I would be highly impressed if someone memorized them! 😆  I think people were copying and pasting the servo ids from the list when you run `modulus project logs tail -p blog` because that would give you the infrastructure provider information and the region info.

Were you thinking more along the lines of just wanting one of the servos randomly i.e. not really caring which servo it is. The consistency may be off though if you scaled and were trying to find an error that was on the servo that _was_ #3.

Just trying to wrap our minds around this, thanks for your help!

**Comment by harlanj** [comment]
I'm going to close this issue for now. If anyone feels value in this PR just reopen it 😄

**Pull request closed without merging**
