### PR TITLE
Fix args passed to project.create from project.deploy command

### LINKED ISSUE #131: Cannot deploy when creating project from project.deploy command
Error occurring on `modulus@v6.2.0`
To recreate error:

```bash
# Make sure you deploy to a project that has not been created.
$ modulus project deploy -p someName
```

```
/Users/Jeremiah/Code/modulus-cli/lib/commands/project.js:554
        return cb(null, createdProject);
               ^

TypeError: cb is not a function
    at /Users/Jeremiah/Code/modulus-cli/lib/commands/project.js:554:16
    at IncomingMessage.<anonymous> (/Users/Jeremiah/Code/modulus-cli/lib/librarian/http.js:134:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### PR DESCRIPTION
**Pull request by harlanj**
Closes #131

### CODE REVIEW

**Comment by musgravejw** [comment]
👍

**Comment by jackboberg** [comment]
:shipit:

**Comment by hassanasad** [comment]
Hi - Thanks for looking into this, However its still not working for me. I resinstalled modulus and still the error is the same.

```
sudo npm uninstall -g modulus
sudo npm install -g modulus
```


Error same:
```
/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 1.4

    at new SemVer (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:293:11)
    at compare (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:566:10)
    at Function.gte (/usr/local/lib/node_modules/modulus/node_modules/semver/semver.js:615:10)
    at Project.isSupported (/usr/local/lib/node_modules/modulus/lib/controllers/project.js:771:17)
    at /usr/local/lib/node_modules/modulus/lib/controllers/project.js:246:34
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by jackboberg** [comment]
@hassanasad we haven't tagged/published this yet. I expect we'll get it out tomorrow, but in the meantime you could try:

`npm install -g onmodulus/modulus-cli#master`

**Comment by hassanasad** [comment]
Ah - Works perfectly! Thanks @jackboberg for all the hard work :)

**Pull request merged**
