### PR TITLE
Do not check runtime if projectType is NOT Meteor or Node.js

### PR DESCRIPTION
**Pull request by harlanj**

### CODE REVIEW

**Comment by musgravejw** [comment]
👍

**Comment by franvarney** [comment]
👍

**Comment by jackboberg** [comment]
Backwards `!`

```
[jack@jove:~/Documents/Projects/modulus/sample-apps/static-api-router]
› modulus deploy -p api-router
Welcome to Modulus
You are logged in as jack
Selecting api-router

[Error] You are deploying a Node.js project to a Static runtime. Please select the correct runtime.
```

**Comment by jackboberg** [comment]
👍 tested locally

**Comment by harlanj** [comment]
I don't like how I can deploy a DNX/PHP/Java/Python project to a node/meteor runtime.

**Pull request merged**
